# Generated by Django 3.2.17 on 2023-12-31 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('time_serv', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CurrentTime',
        ),
    ]
